import type { Tool, Testimonial, Faq, Integration } from '@/types';

export const pdfTools: Tool[] = [
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    icon: 'Minimize2',
    category: 'pdf',
    href: '/pdf-tools/compress-pdf',
    popular: true,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document',
    icon: 'Combine',
    category: 'pdf',
    href: '/pdf-tools/merge-pdf',
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract pages or split by range',
    icon: 'Scissors',
    category: 'pdf',
    href: '/pdf-tools/split-pdf',
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Save specific pages as new PDF',
    icon: 'FileOutput',
    category: 'pdf',
    href: '/pdf-tools/extract-pages',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate pages to the correct orientation',
    icon: 'RotateCw',
    category: 'pdf',
    href: '/pdf-tools/rotate-pdf',
  },
  {
    id: 'delete-pages',
    name: 'Remove Pages',
    description: 'Remove unwanted pages from PDF',
    icon: 'Trash2',
    category: 'pdf',
    href: '/pdf-tools/delete-pages',
  },
  {
    id: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Number pages with custom formatting',
    icon: 'Hash',
    category: 'pdf',
    href: '/pdf-tools/add-page-numbers',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Add text or image watermarks',
    icon: 'Droplets',
    category: 'pdf',
    href: '/pdf-tools/add-watermark',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password security to keep your PDF files protected',
    icon: 'Lock',
    category: 'pdf',
    href: '/pdf-tools/protect-pdf',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from secured PDF documents',
    icon: 'Unlock',
    category: 'pdf',
    href: '/pdf-tools/unlock-pdf',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF into editable DOCX while keeping formatting',
    icon: 'FileText',
    category: 'pdf',
    href: '/pdf-tools/pdf-to-word',
    popular: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX files into clean and shareable PDFs',
    icon: 'FileType',
    category: 'pdf',
    href: '/pdf-tools/word-to-pdf',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page into high-quality JPG images',
    icon: 'Image',
    category: 'pdf',
    href: '/pdf-tools/pdf-to-jpg',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Combine JPG images into a single PDF document',
    icon: 'Images',
    category: 'pdf',
    href: '/pdf-tools/jpg-to-pdf',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract searchable text from scanned PDF documents',
    icon: 'ScanText',
    category: 'pdf',
    href: '/pdf-tools/ocr-pdf',
    new: true,
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Repair damaged PDF files and recover readable content',
    icon: 'Wrench',
    category: 'pdf',
    href: '/pdf-tools/repair-pdf',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Drag, reorder, and arrange PDF pages with ease',
    icon: 'LayoutGrid',
    category: 'pdf',
    href: '/pdf-tools/organize-pdf',
    new: true,
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PPT/PPTX slides into PDF',
    icon: 'FileType',
    category: 'pdf',
    href: '/pdf-tools/powerpoint-to-pdf',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert XLS/XLSX spreadsheets into PDF',
    icon: 'FileType',
    category: 'pdf',
    href: '/pdf-tools/excel-to-pdf',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML documents into PDF',
    icon: 'FileType',
    category: 'pdf',
    href: '/pdf-tools/html-to-pdf',
    comingSoon: true,
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF into editable PPT slides',
    icon: 'FileText',
    category: 'pdf',
    href: '/pdf-tools/pdf-to-powerpoint',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables into XLSX sheets',
    icon: 'FileText',
    category: 'pdf',
    href: '/pdf-tools/pdf-to-excel',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDF files to archival PDF/A format',
    icon: 'FileOutput',
    category: 'pdf',
    href: '/tools/pdf-to-pdfa',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Edit text, images, and layout in PDF pages',
    icon: 'FileText',
    category: 'pdf',
    href: '/pdf-tools/edit-pdf',
    comingSoon: true,
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Crop PDF pages to remove unwanted margins',
    icon: 'Crop',
    category: 'pdf',
    href: '/pdf-tools/crop-pdf',
    comingSoon: true,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add digital or handwritten signatures to PDF files',
    icon: 'FileText',
    category: 'pdf',
    href: '/pdf-tools/sign-pdf',
    comingSoon: true,
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently hide sensitive PDF content',
    icon: 'Trash2',
    category: 'pdf',
    href: '/pdf-tools/redact-pdf',
    comingSoon: true,
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Compare two PDF files and highlight differences',
    icon: 'LayoutGrid',
    category: 'pdf',
    href: '/pdf-tools/compare-pdf',
    comingSoon: true,
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate PDF content to another language',
    icon: 'RefreshCw',
    category: 'pdf',
    href: '/pdf-tools/translate-pdf',
    comingSoon: true,
  },
];

export const imageTools: Tool[] = [
  {
    id: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce image size with quality control',
    icon: 'Minimize2',
    category: 'image',
    href: '/image-tools/compress-image',
    popular: true,
  },
  {
    id: 'resize-image',
    name: 'Resize Image',
    description: 'Resize image dimensions with aspect ratio lock support',
    icon: 'Maximize2',
    category: 'image',
    href: '/image-tools/resize-image',
  },
  {
    id: 'crop-image',
    name: 'Crop Image',
    description: 'Crop images to exact dimensions for perfect framing',
    icon: 'Crop',
    category: 'image',
    href: '/image-tools/crop-image',
  },
  {
    id: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate, flip, and straighten images in one place',
    icon: 'RotateCw',
    category: 'image',
    href: '/image-tools/rotate-image',
  },
  {
    id: 'convert-image',
    name: 'Convert Image',
    description: 'Convert between PNG, JPG, and WEBP formats quickly',
    icon: 'RefreshCw',
    category: 'image',
    href: '/image-tools/convert-image',
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert one or more images into a PDF document',
    icon: 'FileImage',
    category: 'image',
    href: '/image-tools/image-to-pdf',
  },
  {
    id: 'remove-background',
    name: 'Remove Background',
    description: 'Remove image backgrounds automatically with AI precision',
    icon: 'Wand2',
    category: 'image',
    href: '/image-tools/remove-background',
    new: true,
  },
  {
    id: 'passport-photo-maker',
    name: 'Passport Size Photo Maker',
    description: 'Create 413 x 531 passport photo with editable background',
    icon: 'Wand2',
    category: 'image',
    href: '/image-tools/passport-photo-maker',
    new: true,
  },
  {
    id: 'image-watermark',
    name: 'Image Watermark',
    description: 'Add text or logo watermarks to your images',
    icon: 'Droplets',
    category: 'image',
    href: '/image-tools/image-watermark',
  },
];

export const allTools = [...pdfTools, ...imageTools];
export const availablePdfTools = pdfTools;
export const availableImageTools = imageTools;

const commonToolIds = [
  'compress-pdf',
  'merge-pdf',
  'split-pdf',
  'pdf-to-word',
  'compress-image',
  'resize-image',
  'convert-image',
  'remove-background',
];

const toolById = new Map(allTools.map((tool) => [tool.id, tool]));

export const commonTools = commonToolIds
  .map((id) => toolById.get(id))
  .filter((tool): tool is Tool => Boolean(tool));

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'Marketing Director',
    company: 'TechFlow Inc.',
    content: 'EditFile has completely transformed how we handle PDFs. The compression is incredible - we reduced our document sizes by 70% without any quality loss.',
    avatar: 'SC',
    rating: 5,
  },
  {
    id: '2',
    name: 'Marcus Johnson',
    role: 'Freelance Designer',
    company: 'Self-employed',
    content: 'The image tools are fantastic! I use the background removal and compression daily. Fast, reliable, and the quality is always spot on.',
    avatar: 'MJ',
    rating: 5,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'Operations Manager',
    company: 'GlobalDocs Ltd.',
    content: 'We process thousands of PDFs monthly. EditFile\'s batch processing and merge tools save us hours every week. Highly recommended!',
    avatar: 'ER',
    rating: 5,
  },
  {
    id: '4',
    name: 'David Kim',
    role: 'Software Engineer',
    company: 'DevStudio',
    content: 'The OCR feature is a game-changer. Extracting text from scanned documents used to be a pain - now it\'s just drag, drop, done.',
    avatar: 'DK',
    rating: 5,
  },
  {
    id: '5',
    name: 'Lisa Thompson',
    role: 'Content Creator',
    company: 'CreativeHub',
    content: 'I love how intuitive the interface is. No learning curve - just upload and edit. The watermark feature is perfect for protecting my work.',
    avatar: 'LT',
    rating: 5,
  },
];

export const faqs: Faq[] = [
  {
    id: '1',
    question: 'Is EditFile free to use?',
    answer: 'Yes! EditFile offers a generous free tier with essential features. You can compress, convert, merge, and edit files without any cost.',
  },
  {
    id: '2',
    question: 'Are my files secure?',
    answer: 'Absolutely. We use bank-level encryption (AES-256) for all file transfers. Your files are automatically deleted from our servers after 1 hour, and we never access or share your content with third parties.',
  },
  {
    id: '3',
    question: 'What file formats are supported?',
    answer: 'We support all major formats including PDF, Word (DOCX), Excel (XLSX), PowerPoint (PPTX), JPG, PNG, WEBP, HEIC, and TIFF. Our conversion tools maintain formatting and quality whenever possible.',
  },
  {
    id: '4',
    question: 'Is there a file size limit?',
    answer: 'No strict upload size cap is enforced by the app. Large files can still depend on browser and server memory availability.',
  },
  {
    id: '5',
    question: 'Can I process multiple files at once?',
    answer: 'Yes! Our batch processing feature allows you to upload and process multiple files simultaneously. You can also merge multiple PDFs or images into a single document.',
  },
  {
    id: '6',
    question: 'Do I need to install any software?',
    answer: 'Not at all. EditFile is completely web-based and works in any modern browser. No downloads, no installations, no updates - just open the website and start editing.',
  },
  {
    id: '7',
    question: 'How accurate is the OCR feature?',
    answer: 'Our OCR supports 100+ languages with 95%+ accuracy for clear, high-quality scans. For best results, ensure your documents have good contrast and minimal skew.',
  },
  {
    id: '8',
    question: 'Can I use EditFile on mobile?',
    answer: 'Yes! EditFile is fully responsive and works great on smartphones and tablets. You can process files on the go from any device with a web browser.',
  },
];

export const integrations: Integration[] = [
  {
    id: '1',
    name: 'Google Drive',
    icon: 'Drive',
    description: 'Import and export directly from Google Drive',
  },
  {
    id: '2',
    name: 'Dropbox',
    icon: 'Box',
    description: 'Seamless Dropbox integration',
  },
  {
    id: '3',
    name: 'OneDrive',
    icon: 'Cloud',
    description: 'Connect with Microsoft OneDrive',
  },
  {
    id: '4',
    name: 'iCloud',
    icon: 'Cloud',
    description: 'Import from Apple iCloud',
  },
  {
    id: '5',
    name: 'Box',
    icon: 'Box',
    description: 'Enterprise Box integration',
  },
  {
    id: '6',
    name: 'Notion',
    icon: 'FileText',
    description: 'Export to Notion pages',
  },
  {
    id: '7',
    name: 'Slack',
    icon: 'MessageSquare',
    description: 'Share files directly to Slack',
  },
  {
    id: '8',
    name: 'Figma',
    icon: 'Figma',
    description: 'Export images for Figma',
  },
];

export const features = [
  {
    id: 'speed',
    title: 'Lightning Fast',
    description: 'Process files in seconds with our optimized cloud infrastructure',
    icon: 'Zap',
  },
  {
    id: 'security',
    title: 'Bank-Level Security',
    description: 'AES-256 encryption with automatic file deletion after 1 hour',
    icon: 'Shield',
  },
  {
    id: 'free',
    title: 'Free Forever',
    description: 'All essential features available at no cost, no credit card required',
    icon: 'Gift',
  },
  {
    id: 'cloud',
    title: 'Cloud Processing',
    description: 'No local resources used - everything happens in the cloud',
    icon: 'Cloud',
  },
];

export const howItWorks = [
  {
    step: 1,
    title: 'Upload',
    description: 'Drag and drop your files or click to browse. We support PDF, images, and documents.',
    icon: 'Upload',
  },
  {
    step: 2,
    title: 'Process',
    description: 'Choose your tool and settings. Our servers handle the heavy lifting instantly.',
    icon: 'Settings',
  },
  {
    step: 3,
    title: 'Download',
    description: 'Get your processed files immediately. No waiting, no watermarks.',
    icon: 'Download',
  },
];

